name: Remote SSH Command
on:
  push:
    branches:
      - main

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH command
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PW }}
          script: sh ~/fe/front/deploy.sh
